feature_map <- list()
# names of features
feature_map$name <-
  c(
    "cluster_origin",
    "bocc_origin",
    "year",
    "cluster_method",
    "subcluster_method",
    "IDs",
    "cluster_size",
    "gene_ratio",
    "HPO_ratio",
    "num_sig_go_enrichment_terms",
    "sig_go_enrichment_p_vals",
    "sig_go_enrichment_fdr_corrected_p_vals",
    "sig_go_enrichment_terms",
    "go_sig_threshold",
    "max_norm_cell_type_specificity",
    "max_norm_cell_type_comma_sep_string",
    "num_of_diseases",
    "max_norm_disease_specificity",
    "max_norm_disease_comma_sep_string",
    "mg2_pairs_count",
    "mg2_not_pairs_count",
    "mg2_portion_families_recovered",
    "avg_embeddedness",
    "avg_internal_degree",
    "conductance",
    "cut_ratio",
    "normalized_cut",
    "expansion",
    "triangle_participation_ratio",
    "surprise",
    "significance",
    "newman_girvan_modularity",
    "internal_edge_density",
    "edges_inside",
    "hub_dominance",
    "max_plof",
    "mean_plof",
    "median_plof",
    "std_plof",
    "sum_plof",
    "snowballing_pvalue",
    "num_new_edges_on_any_node"
  )

# whether the features are ids, responses, network covariates, or biological covariates
feature_map$category <- c(
  "cluster_origin" = "id",
  "bocc_origin" = "id",
  "year" = "id",
  "cluster_method" = "id",
  "subcluster_method" = "id",
  "IDs" = "id",
  "cluster_size" = "net",
  "gene_ratio" = "net",
  "HPO_ratio" = "net",
  "num_sig_go_enrichment_terms" = "bio",
  "sig_go_enrichment_p_vals" = "bio",
  "sig_go_enrichment_fdr_corrected_p_vals" = "bio",
  "sig_go_enrichment_terms" = "bio",
  "go_sig_threshold" = "id",
  "max_norm_cell_type_specificity" = "bio",
  "max_norm_cell_type_comma_sep_string" = "bio",
  "num_of_diseases" = "bio",
  "max_norm_disease_specificity" = "bio",
  "max_norm_disease_comma_sep_string" = "bio",
  "mg2_pairs_count" = "response",
  "mg2_not_pairs_count" = "response",
  "mg2_portion_families_recovered" = "response",
  "avg_embeddedness" = "net",
  "avg_internal_degree" = "net",
  "conductance" = "net",
  "cut_ratio" = "net",
  "normalized_cut" = "net",
  "expansion" = "net",
  "triangle_participation_ratio" = "net",
  "surprise" = "net",
  "significance" = "net",
  "newman_girvan_modularity" = "net",
  "internal_edge_density" = "net",
  "edges_inside" = "net",
  "hub_dominance" = "net",
  "max_plof" = "bio",
  "mean_plof" = "bio",
  "median_plof" = "bio",
  "std_plof" = "bio",
  "sum_plof" = "bio",
  "snowballing_pvalue" = "response",
  "num_new_edges_on_any_node" = "response"
)

# what the ideal data type should be
feature_map$type <-
  c(
    "cluster_origin" = "character",
    "bocc_origin" = "character",
    "year" = "character",
    "cluster_method" = "character",
    "subcluster_method" = "character",
    "IDs" = "double",
    "cluster_size" = "double",
    "gene_ratio" = "double",
    "HPO_ratio" = "double",
    "num_sig_go_enrichment_terms" = "double",
    "sig_go_enrichment_p_vals" = "list",
    "sig_go_enrichment_fdr_corrected_p_vals" = "list",
    "sig_go_enrichment_terms" = "list",
    "go_sig_threshold" = "double",
    "max_norm_cell_type_specificity" = "double",
    "max_norm_cell_type_comma_sep_string" = "list",
    "num_of_diseases" = "double",
    "max_norm_disease_specificity" = "double",
    "max_norm_disease_comma_sep_string" = "list",
    "mg2_pairs_count" = "double",
    "mg2_not_pairs_count" = "double",
    "mg2_portion_families_recovered" = "double",
    "avg_embeddedness" = "double",
    "avg_internal_degree" = "double",
    "conductance" = "double",
    "cut_ratio" = "double",
    "normalized_cut" = "double",
    "expansion" = "double",
    "triangle_participation_ratio" = "double",
    "surprise" = "double",
    "significance" = "double",
    "newman_girvan_modularity" = "double",
    "internal_edge_density" = "double",
    "edges_inside" = "double",
    "hub_dominance" = "double",
    "max_plof" = "double",
    "mean_plof" = "double",
    "median_plof" = "double",
    "std_plof" = "double",
    "sum_plof" = "double",
    "snowballing_pvalue" = "double",
    "num_new_edges_on_any_node" = "double"
  )

usethis::use_data(feature_map, overwrite = TRUE)
